---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core
    icinga: https://github.com/voxpupuli/puppet-icinga
    redis: https://github.com/voxpupuli/puppet-redis
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core
    zypprepo: https://github.com/voxpupuli/puppet-zypprepo
